const USER_ELEMENT_UPDATED_ADD = "USER_ELEMENT_UPDATED_ADD";
const USER_ELEMENT_UPDATED_REMOVE = "USER_ELEMENT_UPDATED_REMOVE";

export default {
    USER_ELEMENT_UPDATED_ADD,
    USER_ELEMENT_UPDATED_REMOVE
};